steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--build-arg", "DOCKER_BUILDKIT=1", "--tag", "gcr.io/paper-tools/superset", "."]
options:
  env:
    - DOCKER_BUILDKIT=1
  machineType: 'e2-highmem-8'
images:
  - "gcr.io/paper-tools/superset"
